"""Application constants."""

SERVICE_NAME = "Finance Incident Multi-Agent"
SERVICE_VERSION = "1.8.0"
DEFAULT_ENVIRONMENT = "local"
DEFAULT_LOG_LEVEL = "INFO"

DEFAULT_CURRENCY = "USD"
SUPPORTED_CURRENCIES = frozenset({"USD", "EUR", "MAD", "GBP", "CAD"})

RISK_LEVEL_LOW = "low"
RISK_LEVEL_MEDIUM = "medium"
RISK_LEVEL_HIGH = "high"
RISK_LEVELS = frozenset({RISK_LEVEL_LOW, RISK_LEVEL_MEDIUM, RISK_LEVEL_HIGH})

COMPLIANCE_STATUS_COMPLIANT = "compliant"
COMPLIANCE_STATUS_REVIEW_REQUIRED = "review_required"
COMPLIANCE_STATUS_BLOCKED = "blocked"
COMPLIANCE_STATUSES = frozenset(
    {
        COMPLIANCE_STATUS_COMPLIANT,
        COMPLIANCE_STATUS_REVIEW_REQUIRED,
        COMPLIANCE_STATUS_BLOCKED,
    }
)

DECISION_ACCEPTED = "accepted"
DECISION_REVIEW_REQUIRED = "review_required"
DECISION_REJECTED = "rejected"
DECISIONS = frozenset({DECISION_ACCEPTED, DECISION_REVIEW_REQUIRED, DECISION_REJECTED})
